name: ac_fetch
description: An easy to use HTTP data fetcher with HTTP1/2 and integrated HTTP cache support
version: 0.1.1
repository: https://github.com/anthochamp/dart-fetch.git

environment:
  sdk: '>=2.19.5 <4.0.0'

dependencies:
  ac_dart_essentials: ^0.2.1
  ac_httpx_client: ^0.1.0
  async: ^2.10.0
  freezed_annotation: ^2.2.0

dev_dependencies:
  ac_lints: ^0.2.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  import_sorter: ^4.6.0
  test: ^1.24.2
