name: fetch
publish_to: 'none'
version: 1.0.0
repository: https://github.com/anthochamp/dart-fetch.git

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  anthochamp_dart_essentials:
    git: git@github.com:anthochamp/dart-essentials.git
  async: ^2.10.0
  freezed_annotation: ^2.2.0
  httpx_client:
    git: git@github.com:anthochamp/dart-httpx-client.git

dev_dependencies:
  anthochamp_lints:
    git: git@github.com:anthochamp/dart-lints.git
  build_runner: ^2.3.3
  dart_code_metrics: ^5.7.2
  freezed: ^2.3.2
  import_sorter: ^4.6.0
  lints: ^2.0.1
  test: ^1.24.2
